# runs tests for push-events, for pull requests and using cron schedule:
name: Run Tests
on:
    push:
        branches:
            - main
    schedule:
        - cron: "*/3 * * * *"
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: ls
              run: ls
