# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests
on:
    push:
        # runs tests for commits pushed to master
        branches:
            - master
        # do not run tests if file README.md changes
        paths-ignore:
            - "README.md"
        # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
    pull_request:
        paths-ignore:
            - "README.md"
    schedule:
        # run tests once a year in January 1st
        - cron: "*/3 * * * *"
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            # checkout code from a repository
            - uses: actions/checkout@v2

            # create folder for test reports
            - name: ls
              run: ls