# runs tests for push-events, for pull requests and using cron schedule:
name: Run Tests
on:
    push:
        # runs tests for commits pushed to master
        branches:
            - master
    schedule:
        - cron: "*/3 * * * *"
jobs:
    cron:
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!
