# runs tests for push-events, for pull requests and using cron schedule:
name: Run Tests
on:
    push:
        # runs tests for commits pushed to master
        branches:
            - master
        # do not run tests if file README.md changes
        paths-ignore:
            - "README.md"
        # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
    pull_request:
        paths-ignore:
            - "README.md"
    schedule:
        - cron: "0 0 * * 0"

          # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    cron:
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!
